name: Website Dev Branch Merge
on:
  push:
    branches:
      - main
jobs:
  job:
    name: Sync main to dev
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
      
    steps:
    - name: Checkout main
      uses: actions/checkout@v4
      with:
        ref: main
        
    - name: 'Pull main'
      run: |
        git pull
  
    - name: Checkout dev.yetalittlewhile.com
      uses: actions/checkout@v4
      with:
        ref: dev.yetalittlewhile.com
  
    - name: 'Merge and push to origin/main'
      run: |
        git merge main
        git push origin dev.yetalittlewhile.com
