name: Website Publish (Dev)
on:
  push:
    branches:
      - dev.yetalittlewhile.com
jobs:
  job:
    name: Website Publish (Dev)
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:
    - name: Checkout dev
      uses: actions/checkout@v4
      with:
        ref: dev.yetalittlewhile.com

    - name: Authenticate on GCS
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2    

    - name: 'Rsync to gcs'
      run: 'gcloud storage rsync --recursive --delete-unmatched-destination-objects ./src gs://dev.yetalittlewhile.com'
