
## resources
## https://www.mickaelvieira.com/blog/2020/01/29/deploying-a-static-website-to-google-cloud-storage-with-github-actions.html
## https://mahendranp.medium.com/gcp-workload-identity-federation-with-github-actions-1d320f62417c
## https://github.com/google-github-actions/setup-gcloud

# .github/workflows/my-workflow.yml
name: Website - Production # name of your workflow
on:
  push:
    branches:
      - master # Deployment will be triggered when we will push to the master branch
jobs:
  build:
    name: Publish the latest from the dev branch
    runs-on: ubuntu-latest # the runner in which the job will be executed
    steps:
    - name: Checkout the dev branch
      uses: actions/checkout@v4
      with:
        ref: dev.yetalittlwhile.com

    - name: Authenticate on GCS
      uses: google-github-actions/auth@v2
      with:
        service_account: '${{ secrets.GCP_SA_EMAIL }}'
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: '>= 489.0.0'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

      
